"""Create Shared Accounts table

Revision ID: 229ec1b63c7a
Revises: 2f746d97355d
Create Date: 2026-05-04 19:47:24.102091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229ec1b63c7a'
down_revision: Union[str, Sequence[str], None] = '2f746d97355d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_owner_account', sa.Integer(), nullable=False),
    sa.Column('id_member', sa.Integer(), nullable=False),
    sa.Column('can_view_balance', sa.SmallInteger(), nullable=False),
    sa.Column('can_view_transaction', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_member'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_owner_account'], ['user_accounts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_accounts')
    # ### end Alembic commands ###
