"""Add owner column and rename id_owner_account to id_account

Revision ID: fd2e7727234e
Revises: 229ec1b63c7a
Create Date: 2026-05-05 12:10:29.189247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fd2e7727234e'
down_revision: Union[str, Sequence[str], None] = '229ec1b63c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_accounts', sa.Column('id_owner', sa.Integer(), nullable=False))
    op.add_column('shared_accounts', sa.Column('id_account', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('shared_accounts_ibfk_2'), 'shared_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'shared_accounts', 'user_accounts', ['id_account'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'shared_accounts', 'users', ['id_owner'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('shared_accounts', 'id_owner_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_accounts', sa.Column('id_owner_account', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shared_accounts', type_='foreignkey')
    op.drop_constraint(None, 'shared_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('shared_accounts_ibfk_2'), 'shared_accounts', 'user_accounts', ['id_owner_account'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('shared_accounts', 'id_account')
    op.drop_column('shared_accounts', 'id_owner')
    # ### end Alembic commands ###
